#!/usr/bin/env bash

set -e

for x in build bin; do
    if [ ! -d "$x" ]; then
        mkdir "$x"
    fi
done

for x in terrain.ml io.ml main.ml; do
    if [ "$2" = "lint" ]; then
        ocp-indent -i src/$x
    fi
    cp src/$x build/
done

(
    cd build/
    ocamlopt \
        terrain.ml io.ml main.ml \
        -O3 \
        -w +1..66 \
        -o ../bin/main
)

./bin/main "$1" "$2"
