#!/usr/bin/env bash

target=$1
flag=$2

f () {
    if [ "$flag" == "lint" ]; then
        ocp-indent -i "src/$1.ml"
    fi
    ocaml -w +1..66 "src/$1.ml" < input.txt
}

if [ "$target" == "1" ]; then
    f part1
elif [ "$target" == "2" ]; then
    f part2
fi
